# Generated by Django 3.1.4 on 2020-12-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='user',
        ),
    ]
